name: JSON Lint and Validate

on:
  push:
    paths:
      - '**/*.json'
  pull_request:
    paths:
      - '**/*.json'
  workflow_dispatch:

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint JSON files with jq
        run: |
          echo "Linting JSON files..."
          find . -name '*.json' -print0 | xargs -0 -n1 jq empty

      - name: Install ajv-cli
        run: npm install -g ajv-cli

      - name: Validate JSON against schema
        run: |
          echo "Validating JSON files against schema..."
          for file in $(find . -name '*.json' ! -path './schemas/*'); do
            filename=$(basename "$file" .json)
            schema="./schemas/${filename}.schema.json"
          
            if [[ ! -f "$schema" ]]; then
            echo "Schema file $schema not found for $file"
            exit 1
            fi
          
            echo "Validating $file against $schema"
            ajv validate -s "$schema" -d "$file"
          done
